E2Helper.Descriptions["wsCreateConnection"] = "Creates a Websocket connection with the specified ID to the specified URL (Optionally, ws headers and cookies can be included.)."
E2Helper.Descriptions["wsCanCreate()"] = "Returns 1 if you can create a Websocket connection at the moment, 0 if not."
E2Helper.Descriptions["wsDataClk(n)"] = "Returns 1 if the current execution was caused by a Websocket message being received. Returns 0 otherwise."
E2Helper.Descriptions["wsConnectClk(n)"] = "Returns 1 if the current execution was caused by a Websocket instance succesfully connecting. Returns 0 otherwise."
E2Helper.Descriptions["wsDisconnectClk(n)"] = "Returns 1 if the current execution was caused by a Websocket disconnecting. Returns 0 otherwise."
E2Helper.Descriptions["wsErrorClk(n)"] = "Returns 1 if the current execution was caused by a Websocket encountering an error. Returns 0 otherwise."
E2Helper.Descriptions["wsGetData(n)"] = "Returns the data received by the Websocket, if it received any."
E2Helper.Descriptions["wsGetURL(n)"] = "Returns the current URL this websocket is connected to."
E2Helper.Descriptions["wsGetError(n)"] = "Returns the error that the websocket encountered, if it did."
E2Helper.Descriptions["wsClearMsgQueue(n)"] = "Clears this Websocket's message queue."
E2Helper.Descriptions["wsClose(n)"] = "Closes a websocket. Difference between this and wsForceClose(n) is that wsClose waits for all messages in the queue to finish sending, while wsForceClose(n) closes instantly, without waiting."
E2Helper.Descriptions["wsIsConnected(n)"] = "Returns 1 if this Websocket is connected."
E2Helper.Descriptions["runOnWS(n)"] = "Tells the chip to execute each time a Websocket-related event is triggered. (see functions with Clk)"

